# Python Basics

## 1. Integer/Float

In [6]:
a = 100.199
print(f"The data type of a is '{type(a)}' and the value is '{a}'")
a = int(a)
print(f"after type casting data type of a is '{type(a)}' and the value is '{a}'")
a = str(a)
print(f"Now data type of a is '{type(a)}' and the value is '{a}'")

The data type of a is '<class 'float'>' and the value is '100.199'
after type casting data type of a is '<class 'int'>' and the value is '100'
Now data type of a is '<class 'str'>' and the value is '100'


## 2. List
**Lists are used to store multiple items in a single variable.**

In [7]:
# List can contain multiple data types
a = [1,1,2,3,4,'abc', 1.43]
print(a)

# Adding and deleting data from list

a.append(123)
print(a)
a.remove(1)
print(a)
# List Slicing
# list[start:end:steps]
a[:6:2]

# For loop in list
for i in a:
    print(a)

[1, 1, 2, 3, 4, 'abc', 1.43]
[1, 1, 2, 3, 4, 'abc', 1.43, 123]
[1, 2, 3, 4, 'abc', 1.43, 123]
[1, 2, 3, 4, 'abc', 1.43, 123]
[1, 2, 3, 4, 'abc', 1.43, 123]
[1, 2, 3, 4, 'abc', 1.43, 123]
[1, 2, 3, 4, 'abc', 1.43, 123]
[1, 2, 3, 4, 'abc', 1.43, 123]
[1, 2, 3, 4, 'abc', 1.43, 123]
[1, 2, 3, 4, 'abc', 1.43, 123]


## 3. Dictionaries
**Dictionaries are used to store data values in key:value pairs.**

In [8]:
d = {
    "40110122": {
            "name": "Aryan Amish",
            "roll": "20S115893",
            "branch": "CSE",
            "batch": "2020-2024",
    },
        "40110123": {
            "name": "xyz",
            "roll": "13314212",
            "branch": "CSE",
            "batch": "2020-2024",
    }
}

# Acessing a Value in Dict
d["40110122"]["name"]

# For loop in dict
for i, j in d.items():
    print(f"Key: {i}, \n\tValue: {j}")

Key: 40110122, 
	Value: {'name': 'Aryan Amish', 'roll': '20S115893', 'branch': 'CSE', 'batch': '2020-2024'}
Key: 40110123, 
	Value: {'name': 'xyz', 'roll': '13314212', 'branch': 'CSE', 'batch': '2020-2024'}


## 4. Sets
**Sets are used to store multiple items in a single variable. It has O(1) search time complexity**


In [9]:
s = {1,2,3,4,"hi there", 12.4}
print(s)
# adding items in sets
s.add("hello")
# removing item in sets
s.remove("hi there")
print(s)

# Search Items in sets
print(1 in s)
print('hello' in s)
print(12341 in s)

{1, 2, 3, 4, 12.4, 'hi there'}
{1, 2, 3, 4, 12.4, 'hello'}
True
True
False


## 5. Bool
**bool is a data type which stores only True and False value**

In [10]:
b = False
print(b)

False


## 6. Tuple
**Tuple is just like list but you cannot change the value of tupe once it is defined**


In [11]:
t = (1,2,34)
print(t)

(1, 2, 34)


## 7. For Loop

**For Loop is used for Looping over some data type or looping over a interval**


In [12]:
# this will print the number from 0-9
for i in range(10):
    print(i)

# this will print the items of the list
for i in [1,2,3,4,5]:
    print(i)
print()
# this will print each character of the string
for i in "hi there":
    print(i)

0
1
2
3
4
5
6
7
8
9
1
2
3
4
5

h
i
 
t
h
e
r
e


## 8. While Loop
**With the while loop we can execute a set of statements as long as a condition is true.**


In [13]:
# this loop will print from 0 to 10
a = 0
while a<=10:
    print(a)
    a += 1

0
1
2
3
4
5
6
7
8
9
10


## 9. Input from User

In [14]:
l = list(map(int, input().split()))
print(l)

[5]


## Q. Check if a number is Prime or not

In [15]:
def prime_number(n=None):
    n = int(input("Enter a Number to check if it is Prime: ")) if n is None else n
    is_prime = True
    for i in range(2, n//2):
        if n%i == 0:
            is_prime = False
            break
    print(f"{n} is Prime" if is_prime is True else f"{n} is not Prime")

prime_number()    
prime_number()    

3 is Prime
1 is Prime


## Q. Find the Factorial of a number

In [16]:
def factorial(n=None):
    n = int(input("Enter a number to find the Factorial : ")) if n is None else n
    ans = 1
    for i in range(2, n+1):
        ans *= i
    print(ans)
factorial()
factorial()

60415263063373835637355132068513997507264512000000000
3446381088548184667326770790875951922006976951375582384611003611981639529782351868763804143237672379379846868628577527599609043944010849343355183826916579274876093562728501050027821075609832035303654996749361753195163012769070700485723141551669720900953728011558584003035375928212655846940281367061125645619508966404523085638743763256980870494465156859819224514274661087972929242817912092409671474491631797677547338910924800000000000000000000000000000000000000000000000000000000000


## Q. sum of first and last digits of the number

In [17]:
def sum_first_last_digit():
    n = input("Enter a number: ")
    print(int(n[0])+int(n[-1]))
sum_first_last_digit()
sum_first_last_digit()

9
9


## Q. Palindrome

In [18]:
def palindrome(orignal=None):
    orignal = list(input("Enter any thing: ")) if orignal is None else orignal
    reverse = orignal.copy()
    reverse.reverse()
    if orignal == reverse:
        print("It is a Plindrome")
    else:
        print("It is not a Plindrome")
palindrome()
palindrome()

It is not a Plindrome
It is not a Plindrome


## Q. Count the numbers of digit in a number

In [19]:
def no_of_digits():
    n = input("Enter any number: ")
    print(len(n))
no_of_digits()
no_of_digits()


2
2


## Q. Armstrong Number

In [20]:
def armstrong(n=None):
    num = int(input("Enter a Number: ")) if n is None else n
    sums = 0

    temp = num
    while temp > 0:
       digit = temp % 10
       sums += digit ** 3
       temp //= 10

    if num == sums:
       print(num,"is an Armstrong number")
    else:
       print(num,"is not an Armstrong number")
armstrong()
armstrong()

23 is not an Armstrong number
54 is not an Armstrong number


## **Q. nCr nPr**

In [21]:
def npr():
    n, r = list(map(int, input("Enter a Number to calculate ncr: ").split()))
    print(n,r)
    print(factorial(n)/factorial(n-r))


In [22]:
import numpy as np

In [23]:
a = np.array([6,7,8])
b = np.array([1,2,3])
c = np.array([4,5,6])
abc = np.array([a,b,c])
print(abc)

[[6 7 8]
 [1 2 3]
 [4 5 6]]


In [24]:
print("Shape: ",abc.shape)
print("Size is: ", abc.size)

Shape:  (3, 3)
Size is:  9
